---
- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
  ignore_errors: true

#-  debug:       var=version_already_installed
- name:          Create Binaries directory
  file:          path={{ __tmp_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __logs_dir }} state=directory mode=0755

- name: Download WAS ND V9 Files
  ansible.builtin.get_url:
    url: "{{ was_repository_url }}/{{ item.file_name }}"
    dest: "{{ __tmp_dir }}/{{ item.file_name }}"
    mode: '0755'
    checksum: "sha256:{{ item.check_sum }}"
  loop: "{{ __was_files }}"

- name: Extract WAS ND V9 Files
  ansible.builtin.unarchive:
    src: "{{ __tmp_dir }}/{{ item.file_name }}"
    dest: "{{ __tmp_dir }}/"
    remote_src: no
  loop: "{{ __was_files }}"

- name: Generate WAS Response file
  ansible.builtin.template:
    src: "{{ __tpl_file }}"
    dest: "{{ __rsp_file }}"

- name: Install IBM WAS Software
  ansible.builtin.command:
    cmd: "{{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}"
    chdir: "{{ __tmp_dir }}"
  register: cout
  changed_when: "cout.stdout.find( __version_check ) != -1"

- name: Cleanup Binaries directory
  file:
    path: "{{ __tmp_dir }}"
    state: absent
