---
- name: Cleanup Binaries directory
  ansible.builtin.file:
    path: "{{ __tmp_dir }}"
    state: absent
  when: version_already_installed.rc != 0
  ignore_errors: true

- name: Create Binaries directory
  ansible.builtin.file:
    path: "{{ __tmp_dir }}"
    state: directory
    mode: '0755'
  when: version_already_installed.rc != 0

- name: Create Logs directory
  ansible.builtin.file:
    path: "{{ __logs_dir }}"
    state: directory
    mode: '0755'
  when: version_already_installed.rc != 0

- name: Download WAS Java
  ansible.builtin.get_url:
    url: "{{ was_repository_url }}/{{ item.file_name }}"
    dest: "{{ __tmp_dir }}/{{ item.file_name }}"
    mode: '0755'
    checksum: "sha256:{{ item.check_sum }}"
  loop: "{{ __this_files }}"
  when: version_already_installed.rc != 0

- name: Extract WAS Java
  ansible.builtin.unarchive:
    src: "{{ __tmp_dir }}/{{ item.file_name }}"
    dest: "{{ __tmp_dir }}/"
    remote_src: no
  loop: "{{ __this_files }}"
  when: version_already_installed.rc != 0

- name: Generate Response file
  ansible.builtin.template:
    src: "{{ __tpl_file }}"
    dest: "{{ __rsp_file }}"
  when: version_already_installed.rc != 0

- name: Disable Repository on Installation Manager
  ansible.builtin.replace:
    path: /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
    regexp: '(\s*)RepositoryIsOpen=true(\s*)'
    replace: '\1RepositoryIsOpen=false\2'
    backup: yes
  ignore_errors: true

- name: Install IBM WAS Java SDK
  ansible.builtin.command:
    cmd: "{{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}"
    chdir: "{{ __tmp_dir }}"
  register: cout
  changed_when: "cout.stdout.find(__version_check) != -1"
  when: version_already_installed.rc != 0

- name: Cleanup Binaries directory
  ansible.builtin.file:
    path: "{{ __tmp_dir }}"
    state: absent
  when: version_already_installed.rc != 0
